"use client";

import { useState } from "react";
import {
  ShieldCheck,
  Lock,
  FileCheck,
  ChevronDown,
  ChevronUp,
  Copy,
  Check,
  Cpu,
  GlobeX,
  Fingerprint,
} from "lucide-react";

export interface ProvenanceRecord {
  generated_by?: string;
  task_type?: string;
  timestamp?: string;
  source_documents?: string[];
  network_status?: string;
  system?: string;
}

export default function ProvenanceBadge({
  provenance,
  filename,
}: {
  provenance?: ProvenanceRecord | null;
  filename?: string | null;
}) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  // Default fallback values if provenance is partially populated
  const record: ProvenanceRecord = {
    generated_by: provenance?.generated_by || "qwen2.5:1.5b-instruct (local, offline)",
    task_type: provenance?.task_type || "document",
    timestamp: provenance?.timestamp || new Date().toISOString(),
    source_documents: provenance?.source_documents || [],
    network_status:
      provenance?.network_status ||
      "Verified offline — 0 external calls during generation",
    system: provenance?.system || "Sovereign AI Workbench v1.0",
  };

  const hasSources = record.source_documents && record.source_documents.length > 0;

  const handleCopyAuditTrail = () => {
    const text = [
      "============================================================",
      " SOVEREIGN AI WORKBENCH — VERIFIED OFFLINE AUDIT CERTIFICATE",
      "============================================================",
      `Generated By    : ${record.generated_by}`,
      `Task Type       : ${record.task_type}`,
      `Timestamp       : ${record.timestamp}`,
      `Network Status  : ${record.network_status}`,
      `System Version  : ${record.system}`,
      `Deliverable File: ${filename || "Text Response"}`,
      "------------------------------------------------------------",
      "SOURCE DOCUMENTS & CRYPTOGRAPHIC SHA-256 FINGERPRINTS:",
      hasSources
        ? record.source_documents?.map((s) => `  - ${s}`).join("\n")
        : "  - No external source documents used — general model knowledge",
      "============================================================",
    ].join("\n");

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="w-full flex flex-col gap-2 my-2 font-sans">
      {/* Sleek Provenance Audit Badge Bar */}
      <div className="flex items-center justify-between bg-slate-50 border border-emerald-200/80 rounded-2xl px-3.5 py-2 shadow-2xs hover:bg-slate-100/70 transition-colors">
        <div className="flex items-center gap-2">
          <div className="flex h-6 w-6 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700">
            <ShieldCheck className="h-4 w-4" />
          </div>
          <span className="text-xs font-semibold text-slate-800 flex items-center gap-1.5">
            Verified Offline Audit Trail
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-medium bg-emerald-100/90 text-emerald-800 border border-emerald-300/60">
              <Lock className="h-2.5 w-2.5" /> 100% Local
            </span>
          </span>
        </div>

        <button
          type="button"
          onClick={() => setExpanded(!expanded)}
          className="flex items-center gap-1 text-[11px] font-medium text-slate-600 hover:text-slate-900 cursor-pointer px-2 py-1 rounded-lg hover:bg-slate-200/50 transition-colors"
        >
          <span>{expanded ? "Hide Details" : "Inspect SHA-256 Audit Trail"}</span>
          {expanded ? (
            <ChevronUp className="h-3.5 w-3.5 text-slate-500" />
          ) : (
            <ChevronDown className="h-3.5 w-3.5 text-slate-500" />
          )}
        </button>
      </div>

      {/* Expandable Audit Details Card */}
      {expanded && (
        <div className="w-full bg-white border border-slate-200 rounded-2xl p-4 shadow-sm animate-in fade-in slide-in-from-top-1 duration-200 text-xs">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3 mb-3">
            <div className="flex items-center gap-2">
              <Fingerprint className="h-4 w-4 text-indigo-600" />
              <span className="font-semibold text-slate-900 text-xs">
                Cryptographic Provenance Certificate
              </span>
            </div>

            <button
              type="button"
              onClick={handleCopyAuditTrail}
              className="flex items-center gap-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 px-2.5 py-1 rounded-xl text-[11px] font-medium cursor-pointer transition-colors"
            >
              {copied ? (
                <Check className="h-3 w-3 text-emerald-600" />
              ) : (
                <Copy className="h-3 w-3 text-slate-600" />
              )}
              <span>{copied ? "Copied Certificate!" : "Copy Certificate"}</span>
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
            {/* Model & System */}
            <div className="flex items-start gap-2 bg-slate-50/70 p-2.5 rounded-xl border border-slate-100">
              <Cpu className="h-4 w-4 text-blue-600 shrink-0 mt-0.5" />
              <div className="flex flex-col">
                <span className="text-[10px] font-medium text-slate-400 uppercase tracking-wider">
                  Generated By
                </span>
                <span className="font-mono text-xs font-semibold text-slate-800">
                  {record.generated_by}
                </span>
              </div>
            </div>

            {/* Network Verification */}
            <div className="flex items-start gap-2 bg-slate-50/70 p-2.5 rounded-xl border border-slate-100">
              <GlobeX className="h-4 w-4 text-emerald-600 shrink-0 mt-0.5" />
              <div className="flex flex-col">
                <span className="text-[10px] font-medium text-slate-400 uppercase tracking-wider">
                  Network Security
                </span>
                <span className="text-xs font-medium text-emerald-700">
                  0 External Network Calls (127.0.0.1)
                </span>
              </div>
            </div>
          </div>

          {/* Source Documents & SHA-256 Hashes */}
          <div className="flex flex-col gap-1.5 bg-slate-900 text-slate-100 p-3 rounded-xl font-mono text-[11px] overflow-x-auto">
            <div className="flex items-center justify-between text-slate-400 pb-1 border-b border-slate-800 text-[10px] uppercase font-sans">
              <span>Source Document(s) & SHA-256 Fingerprint</span>
              <span>RAG / OCR Audit</span>
            </div>

            {hasSources ? (
              record.source_documents?.map((src, i) => (
                <div key={i} className="flex items-center gap-2 text-slate-200 py-0.5">
                  <FileCheck className="h-3.5 w-3.5 text-emerald-400 shrink-0" />
                  <span className="truncate">{src}</span>
                </div>
              ))
            ) : (
              <div className="flex items-center gap-2 text-slate-400 py-0.5 italic">
                <FileCheck className="h-3.5 w-3.5 text-slate-500 shrink-0" />
                <span>No external source documents used — general model knowledge</span>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
